### PR TITLE
All the new features I added

### PR DESCRIPTION
**Pull request by mournguard**
- Renamed some stuff
- Reordered/group @exports 
- Added vertex color constraint
- Added angle constraint
- Added helper to grab a Mesh from a MeshInstance3D
- Added "button" to randomize seed

### CODE REVIEW

**Comment by arcaneenergy** [comment]
Hey, so this looks pretty awesome and I appreciate all these changes! I've tested and tinkered a bit and have a question.

The vertex color placement is a pretty interesting feature, but for some reason I couldn't get it to work. Can you please explain how to make it work? I've setup a simple scene with different colored grounds. In screenshot 1 all values are set to 1 and all instances are visible (which is the expected output). Screenshot 2 shows the red channel set to 0, green and blue at 1. Shouldn't the instances that were on the green floor be visible?





Other than that, it looks pretty good. You could probably optimize the `find_mesh()` function by storing the found mesh_instances in a temporary array before the for-loop, but this is no big deal.

**Comment by mournguard** [comment]
Oh no ! This is probably due to the checks at 346 being "<" instead of "<=" ; 
It only checks that the color on the closest vertex of the raycast is "below" the color defined by the params. In your second case, 
[0,1,0] (ground) is not "<" [0,1,1] (settings)

But it is "<="

Oh yeah keep the mesh would probably help a lot but I was unsure of the various possible uses since I'm only using it where only one mesh (terrain) is on that collision layer. So yeah not sure what happens if you hit multiple meshes.

**Comment by arcaneenergy** [comment]
Unfortunately still can't get it to work :/ Could you maybe create a simple example scene demonstrating the feature or show how to setup a scene where it would work?
Otherwise, I could merge the other features in to the main branch.

**Comment by mournguard** [comment]
Here's one made via godot 4.0.beta14

One thing I came across while setting it up is that the find_mesh method looks for a mesh in the direct parents or children of the hit.collider, so if the mesh is a sibling somewhere, it won't be found. Maybe we could also just have the user set the mesh directly and use it throughout the process, but it would force users to have one scatter node per mesh so I don't think that's right.

[VertexScatter.zip](https://github.com/arcaneenergy/godot-multimesh-scatter/files/10473150/VertexScatter.zip)

image

**Comment by mournguard** [comment]
Maybe finding the mesh could be done differently but if it starts looking at siblings as well then it will basically crawl the whole tree and that's weird. It already kind of doesn't have a way to make sure it's using the right mesh, it just uses the "closest" one.

Let me know if you have any ideas.

**Comment by arcaneenergy** [comment]
Thanks, I see. Yes, the mesh finding could probably be more performant, but I wouldn't worry about it, unless of course the performance is extremely bad in the editor. So far it's been alright.

The problem about finding the right mesh is definitely more difficult. The mesh could be the child of a StaticBody, or the parent of a StaticBody or the mesh could be anywhere else in the scene tree. There's lots of different possibilities. The best is probably give the user a message or write in the readme how to structure the levels, which isn't a good solution, but would work good enough most of the time.

**Comment by mournguard** [comment]
I can't see a good way to find the mesh and even requiring users to supply a list of potential meshes would mean it'd have to crawl all the vertices of all those meshes to really find the closest one.

I'll add a warning and remove the weird crawling so that it just looks for a mesh in the children of `hit.collider`.

**Comment by arcaneenergy** [comment]
Thanks. I think it'd be better to skip the instances that don't match the angle constraints check and the vertex color check, instead of setting them to zero scale.

**Comment by mournguard** [comment]
Can't really skip them as the internal MultiMesh will render the specified amount no matter what, so if they're not hidden like that they'll just keep their previous position. There can probably be a more elegant solution of reducing the instance count dynamically as needed but I felt like that could wait.

**Comment by arcaneenergy** [comment]
Yes, agreed. I thought of skipping them to reduce the number of calculations in the for-loop, but in the end it doesn't really matter.

If you think all looks good, I could merge it. You can notify me, if you need to make some changes.

**Comment by mournguard** [comment]
It's definitely worth trying to figure out but I think it can be pushed like that anyway.

I added another feature on my end; The vertex color check can become very slow when you have a lot of instances so I made it so that once checked, you need to manually update the scattering so that godot doesn't freeze whenever you make a change.

**Comment by mournguard** [comment]
But I *am* pushing it with 100k x 40 triangles.
image

**Comment by mournguard** [comment]
I'm cleaning up everything and merging with your changes at the moment.

I will also be backtracking on what I said about the mesh search ;
It should look for the mesh in the parents.
- It's more handy with imported meshes if you want to avoid having to do "Make Local" ( You can add children to imports but not reparent them)
- The Godot mesh tools to create collision static bodies automatically add the collision nodes as children of the mesh.

**Comment by mournguard** [comment]
That's it. The next steps should be to better handle hidden meshes but that should be it for this PR.

**Comment by arcaneenergy** [comment]
Looks good so far. One thing I've noticed, is that the instances sometimes don't check their ground in the editor, while it looks correct in the game.

https://user-images.githubusercontent.com/52855634/213937728-28c3037a-e812-40cc-9d57-1e811d92f3e8.mp4

**Comment by arcaneenergy** [comment]
Actually, I simply solved it by setting the instance count to 0 and then setting the actual count.

```
multimesh.instance_count = 0 # new
multimesh.instance_count = count
```

**Comment by arcaneenergy** [comment]
Thanks!

**Pull request merged**
